name: Back-end build and test

on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: "Install dependencies"
        run: npm ci
      - name: "Lint"
        run: npm run lint
      - name: "Compile"
        run: npm run compile
      
        
        
  
